### ISSUE TITLE
Jenkins Job fail

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#29]
Many Jenkins Job fail with this error message. Usually it works when I hit build again for some times but this is very annoying and leads to a lot of questions like "we is my update not deployed on freme-dev?"

```
FATAL: java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2234)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
	at jenkins.security.UserDetailsCache.loadUserByUsername(UserDetailsCache.java:127)
	at hudson.model.User$UserIDCanonicalIdResolver.resolveCanonicalId(User.java:1064)
	at hudson.model.User.get(User.java:398)
	at hudson.model.User.get(User.java:367)
	at hudson.plugins.git.GitChangeSet.findOrCreateUser(GitChangeSet.java:374)
	at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:435)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:350)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:346)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
	at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:542)
	at jenkins.security.UserDetailsCache$Retriever.call(UserDetailsCache.java:172)
	at jenkins.security.UserDetailsCache$Retriever.call(UserDetailsCache.java:161)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
	... 15 more
```

**Comment by jnehring** [comment]
As suggested in a Jenkins forum, I restarted Jenkins. It seems it works better now. I leave this issue open because I am not sure if it is really fixed now.

**Comment by jnehring** [comment]
I upgraded Jenkins to the latest version and restarted. The problem seems to be gone.

**Comment by jnehring** [comment]
The bug still occurs

**Comment by jnehring** [comment]
I upgraded all the plugins also. Then I build 5 jobs and the error did not occur once. So I think it is fixed.
